### ISSUE TITLE
distinctions between healthy/underweight/overweight not consistent.

### ISSUE THREAD

**Issue by ZekeZDev** [PhilippKosarev/bmi#2]
The way its doing distinctions of healthy and underweight/overweight is not consistent. I am assuming its stuck on a between value. but basically with testing at 200cm and changing the height 69-74kg was considered underweight if the counter was on 69 originally, however if the counter was on 75 then 75-70kg are considered healthy. same with 98+ being overweight but if you start at 99 then 99-94 are also overweight.

**Comment by philippkosarev** [comment]
Hey! Thanks for the report.
This should be fixed in 0e8893e787323a480d39105535f476b507e34b3e.
If this bug persists in the next release please feel free to reopen the issue.
